condense_wildcard_suffixes = true
fn_call_width = 40                  # 60
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Crate"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 80  # 50
single_line_let_else_max_width = 80 # 50
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
