#!/bin/sh
# Usage: ./run.sh [check] [release|trace|web] [args...]

# Debug builds
ARGS="--features dev --no-default-features $@"

# Check build
if [ "$1" = "check" ]; then
    shift
    ARGS="--features dev --no-default-features $@"
    cargo fmt --all
    cargo clippy --allow-dirty --allow-staged --fix $ARGS
    exit
fi

# Local web build
if [ "$1" = "web" ]; then
    shift
    ARGS="--features dev --no-default-features $@"
    trunk serve $ARGS
    exit
fi

# Release mode
if [ "$1" = "release" ]; then
    shift
    ARGS="--release $@"
fi

# Trace mode
if [ "$1" = "trace" ]; then
    shift
    ARGS="--release --features bevy/trace_tracy $@"
    tracy-capture -o capture.tracy &
fi

if [ "$1" = "ftrace" ]; then
    shift
    ARGS="--release --features bevy/trace_tracy $@"
    TRACY=true
    tracy-capture -o capture.tracy -f &
fi

cargo run $ARGS

if [ $TRACY ]; then
    tracy capture.tracy
fi
