# Fast build

# NOTE: For maximum performance, build using a nightly compiler
# If you are using rust stable, remove the "-Zshare-generics=y" below.
# You need to install mold for the fastest compile, else change /usr/bin/mold to lld

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=/usr/bin/mold",
    "-Zshare-generics=y"
]

# NOTE: You must install [Mach-O LLD Port](https://lld.llvm.org/MachO/index.html) on mac
# You can easily do this by installing llvm which includes lld with the "brew" package manager: `brew install llvm`

[target.x86_64-apple-darwin]
rustflags = [
    "-Clink-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",
    "-Zshare-generics=y",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",
    "-Zshare-generics=y",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n"]
